(source gnu)
(source marmalade)
(source melpa)
(source melpa-stable)

(depends-on "cask")
(depends-on "dash")
(depends-on "enh-ruby-mode")
(depends-on "epl")
(depends-on "evil")
(depends-on "evil-tabs")
(depends-on "f")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "s")
(depends-on "shut-up")
(depends-on "slim-mode")
